apiVersion: extensions/v1beta1  
kind: Ingress  
metadata:  
  name: funayose-test-ingress
  namespace: sandbox
spec:  
  tls:
  - secretName: funayose-test-ssl
  backend:
    serviceName: idp-service
    servicePort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: idp-service
  namespace: sandbox
  labels:
    app: idp
spec:
  type: NodePort
  ports:
  - port: 7000
    targetPort: 7000
    protocol: TCP
  selector:
    app: idp
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: idp
  namespace: sandbox
spec:
  replicas: 2
  revisionHistoryLimit: 5
  template:
    metadata:
      namespace: sandbox
      labels:
        app: idp
        version: latest
    spec:
      containers:
      - name: idp
        image: asia.gcr.io/linkbal-sandbox/idp:latest
        ports:
        - containerPort: 7000