apiVersion: v1
kind: Service
metadata:
  name: fuga-api
  namespace: fuga-namespace
  labels:
    app: fuga-api
spec:
  type: (LoadBalancer->) NodePort
  ports:
  - port: (80->)8080 
    targetPort: 8080
    protocol: TCP
  selector:
    app: fuga-api
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: idp
  namespace: idp-namespace
spec:
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      namespace: idp-namespace
      labels:
        app: idp
        version: latest
    spec:
      containers:
      - name: idp
        image: asia.gcr.io/linkbal-sandbox/idp:latest
        ports:
        - containerPort: 7000